# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=40)),
                ('feedback_text', models.CharField(max_length=2000)),
                ('feedback_date', models.DateTimeField(auto_now=True)),
                ('feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=64)),
                ('goods_pic', models.ImageField(default='default_pic', upload_to='')),
                ('goods_price', models.FloatField(default=99.9)),
                ('goods_amount', models.IntegerField(default=1488)),
                ('goods_description', models.TextField()),
                ('goods_producer', models.CharField(max_length=32)),
                ('goods_producer_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='GoodsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=800)),
                ('comment_date', models.DateField(auto_now=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_gallery_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('goods_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_count', models.IntegerField()),
                ('rate_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Goods')),
            ],
        ),
    ]
